// Registry of every calculator exposed by this library, with keyword-rich
// SEO metadata for the web UI dynamic renderer. High-volume HSE and EHS
// search terms are baked in per-entry.

import type { CalculatorMeta } from "./types";

export const CALCULATORS: CalculatorMeta[] = [
  // ── Incident rates ─────────────────────────────────────────────────────
  {
    slug: "trir-calculator",
    name: "TRIR Calculator",
    category: "incident-rates",
    shortDescription: "OSHA Total Recordable Incident Rate",
    seoTitle: "TRIR Calculator — OSHA Total Recordable Incident Rate Formula (Free)",
    seoDescription:
      "Free TRIR calculator using the OSHA formula: (Recordable Incidents × 200,000) ÷ Hours Worked. Required for OSHA 300A, insurance EMR, Aramco/ADNOC prequalification.",
    keywords: [
      "TRIR calculator",
      "total recordable incident rate",
      "OSHA TRIR formula",
      "OSHA 300A",
      "OSHA recordable incidents",
      "TRIR formula",
      "workplace safety metrics",
      "HSE KPI",
      "OSHA compliance software",
      "Aramco TRIR",
      "ADNOC HSE",
      "construction TRIR benchmark",
      "oil and gas TRIR",
      "manufacturing TRIR benchmark",
    ],
    formula: "TRIR = (Recordable Incidents × 200,000) ÷ Hours Worked",
    regulation: "OSHA 29 CFR 1904.7",
    regulationUrl: "https://www.osha.gov/laws-regs/regulations/standardnumber/1904/1904.7",
    inputs: [
      {
        id: "recordableIncidents",
        label: "Recordable incidents",
        type: "number",
        min: 0,
        step: 1,
        defaultValue: 3,
        help: "All OSHA 300-recordable injuries and illnesses for the reporting period.",
      },
      {
        id: "hoursWorked",
        label: "Total hours worked",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 500_000,
        help: "Sum of all employee hours worked during the reporting period.",
      },
    ],
  },
  {
    slug: "ltir-calculator",
    name: "LTIR Calculator",
    category: "incident-rates",
    shortDescription: "OSHA Lost Time Incident Rate",
    seoTitle: "LTIR Calculator — Lost Time Incident Rate Formula (OSHA 200,000 Base)",
    seoDescription:
      "Free Lost Time Incident Rate calculator using the OSHA 200,000-hour base. LTIR = (Lost Time Incidents × 200,000) ÷ Hours Worked.",
    keywords: [
      "LTIR calculator",
      "lost time incident rate",
      "OSHA LTIR formula",
      "LTI rate",
      "lost time injury",
      "workplace injury rate",
      "safety performance KPI",
      "OSHA compliance",
      "ISO 45001 monitoring",
    ],
    formula: "LTIR = (Lost Time Incidents × 200,000) ÷ Hours Worked",
    regulation: "OSHA 29 CFR 1904.7(b)(3)",
    inputs: [
      {
        id: "lostTimeIncidents",
        label: "Lost time incidents",
        type: "number",
        min: 0,
        step: 1,
        defaultValue: 2,
      },
      {
        id: "hoursWorked",
        label: "Total hours worked",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 500_000,
      },
    ],
  },
  {
    slug: "ltifr-calculator",
    name: "LTIFR Calculator",
    category: "incident-rates",
    shortDescription: "ISO/ILO Lost Time Injury Frequency Rate",
    seoTitle: "LTIFR Calculator — Lost Time Injury Frequency Rate Formula (1,000,000 Base)",
    seoDescription:
      "Free LTIFR calculator using the ISO/ILO 1,000,000-hour base. Used by HSE UK, IOGP, GCC (UAE, Saudi Arabia, Qatar), and ISO 45001 worldwide.",
    keywords: [
      "LTIFR calculator",
      "lost time injury frequency rate",
      "LTIFR formula",
      "ILO LTIFR",
      "ISO 45001 LTIFR",
      "HSE UK LTIFR",
      "IOGP HSE metrics",
      "international safety KPI",
      "GCC safety metrics",
      "UAE HSE software",
      "Saudi Arabia HSE software",
    ],
    formula: "LTIFR = (Lost Time Injuries × 1,000,000) ÷ Hours Worked",
    regulation: "ILO / ISO 45001:2018",
    inputs: [
      {
        id: "lostTimeInjuries",
        label: "Lost time injuries",
        type: "number",
        min: 0,
        step: 1,
        defaultValue: 3,
      },
      {
        id: "hoursWorked",
        label: "Total hours worked",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 500_000,
      },
    ],
  },
  {
    slug: "dart-rate-calculator",
    name: "DART Rate Calculator",
    category: "incident-rates",
    shortDescription: "OSHA Days Away, Restricted, Transferred rate",
    seoTitle: "DART Rate Calculator — Days Away, Restricted, Transferred (OSHA Formula)",
    seoDescription:
      "Free DART rate calculator: (DART Cases × 200,000) ÷ Hours Worked. Used in OSHA VPP evaluation and BLS SOII benchmarking.",
    keywords: [
      "DART rate calculator",
      "DART rate formula",
      "OSHA DART",
      "days away restricted transferred",
      "OSHA VPP",
      "BLS SOII",
      "OSHA benchmark",
      "safety metrics US",
    ],
    formula: "DART Rate = (DART Cases × 200,000) ÷ Hours Worked",
    regulation: "OSHA 29 CFR 1904.7(a)",
    inputs: [
      { id: "dartCases", label: "DART cases", type: "number", min: 0, step: 1, defaultValue: 2 },
      {
        id: "hoursWorked",
        label: "Total hours worked",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 500_000,
      },
    ],
  },
  {
    slug: "severity-rate-calculator",
    name: "Severity Rate Calculator",
    category: "incident-rates",
    shortDescription: "Days lost per exposure base",
    seoTitle: "Severity Rate Calculator — Days Lost / Hours Worked (OSHA + ILO)",
    seoDescription:
      "Free severity rate calculator with both OSHA (200,000) and ISO/ILO (1,000,000) base support. Required KPI for ISO 45001 management review.",
    keywords: [
      "severity rate calculator",
      "severity rate formula",
      "days lost calculator",
      "OSHA severity rate",
      "ISO 45001 severity",
      "HSE severity",
      "safety severity KPI",
    ],
    formula: "Severity Rate = (Days Lost × Base) ÷ Hours Worked",
    regulation: "OSHA / ILO",
    inputs: [
      { id: "daysLost", label: "Days lost", type: "number", min: 0, step: 1, defaultValue: 45 },
      {
        id: "hoursWorked",
        label: "Total hours worked",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 500_000,
      },
      {
        id: "base",
        label: "Base",
        type: "select",
        defaultValue: "osha",
        options: [
          { value: "osha", label: "OSHA (200,000)" },
          { value: "iso", label: "ISO/ILO (1,000,000)" },
        ],
      },
    ],
  },
  {
    slug: "frequency-rate-calculator",
    name: "Frequency Rate Calculator",
    category: "incident-rates",
    shortDescription: "International accident frequency rate",
    seoTitle: "Accident Frequency Rate Calculator — International (1,000,000 Base)",
    seoDescription:
      "Calculate Accident Frequency Rate (AFR) using the international 1,000,000-hour base. Used by HSE UK, IOGP, ADNOC, Aramco, QatarEnergy.",
    keywords: [
      "accident frequency rate calculator",
      "AFR calculator",
      "HSE UK frequency rate",
      "IOGP frequency rate",
      "ADNOC HSE",
      "Aramco HSE",
      "QatarEnergy HSE",
      "international safety metrics",
    ],
    formula: "AFR = (Reportable Accidents × 1,000,000) ÷ Hours Worked",
    regulation: "HSE UK / IOGP",
    inputs: [
      { id: "accidents", label: "Reportable accidents", type: "number", min: 0, step: 1, defaultValue: 5 },
      {
        id: "hoursWorked",
        label: "Total hours worked",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 2_000_000,
      },
    ],
  },
  {
    slug: "emr-calculator",
    name: "EMR Calculator",
    category: "cost",
    shortDescription: "Workers Compensation Experience Modification Rate",
    seoTitle: "EMR Calculator — Experience Modification Rate (Workers Comp Premium Multiplier)",
    seoDescription:
      "Free EMR (Experience Modification Rate) calculator. Directly impacts workers compensation premium. EMR below 1.0 saves money; above 1.0 costs more.",
    keywords: [
      "EMR calculator",
      "experience modification rate",
      "workers compensation EMR",
      "NCCI EMR",
      "insurance EMR",
      "safety insurance",
      "contractor prequalification EMR",
      "construction EMR",
    ],
    formula: "EMR = Actual Losses ÷ Expected Losses",
    regulation: "NCCI / State Workers Comp Bureau",
    inputs: [
      {
        id: "actualLosses",
        label: "Actual losses ($)",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 150_000,
      },
      {
        id: "expectedLosses",
        label: "Expected losses ($)",
        type: "number",
        min: 0,
        step: 1000,
        defaultValue: 200_000,
      },
    ],
  },
  {
    slug: "incident-cost-calculator",
    name: "Incident Cost Calculator",
    category: "cost",
    shortDescription: "Direct + indirect cost per incident (OSHA $afety Pays)",
    seoTitle: "Incident Cost Calculator — OSHA $afety Pays Direct + Indirect Model",
    seoDescription:
      "Estimate true cost of workplace incidents including indirect costs. Based on OSHA $afety Pays ratios. Includes revenue-to-cover calculation.",
    keywords: [
      "incident cost calculator",
      "OSHA safety pays",
      "cost of workplace injury",
      "direct indirect cost",
      "safety ROI calculator",
      "workers comp cost",
      "safety business case",
    ],
    formula: "Total = Direct + (Direct × indirect-ratio)",
    regulation: "OSHA $afety Pays",
    inputs: [
      { id: "directCost", label: "Direct cost ($)", type: "number", min: 0, step: 100, defaultValue: 10_000 },
      {
        id: "severity",
        label: "Severity",
        type: "select",
        defaultValue: "medical",
        options: [
          { value: "firstAid", label: "First aid only" },
          { value: "medical", label: "Medical treatment" },
          { value: "restricted", label: "Restricted duty" },
          { value: "lostTime", label: "Lost time" },
          { value: "fatality", label: "Fatality" },
        ],
      },
    ],
  },

  // ── Exposure ───────────────────────────────────────────────────────────
  {
    slug: "noise-dose-calculator",
    name: "Noise Dose Calculator",
    category: "exposure",
    shortDescription: "Daily noise dose and TWA",
    seoTitle: "Noise Dose Calculator — OSHA 29 CFR 1910.95 (8-Hour TWA)",
    seoDescription:
      "Free noise dose calculator per OSHA 29 CFR 1910.95 (5 dB exchange rate) or ACGIH/EU (3 dB). Returns 8-hour TWA and action-level exceedances.",
    keywords: [
      "noise dose calculator",
      "OSHA noise exposure",
      "29 CFR 1910.95",
      "8-hour TWA noise",
      "hearing conservation",
      "occupational noise",
      "ACGIH noise TLV",
      "EU noise directive",
      "industrial noise",
    ],
    formula: "TWA = 90 + Q × log₂(hours / permissible hours)",
    regulation: "OSHA 29 CFR 1910.95 / ACGIH / EU 2003/10/EC",
    inputs: [
      { id: "leq", label: "Leq (dB(A))", type: "number", min: 0, max: 140, step: 0.1, defaultValue: 92 },
      { id: "hours", label: "Exposure hours", type: "number", min: 0, max: 24, step: 0.25, defaultValue: 8 },
      {
        id: "exchangeRate",
        label: "Exchange rate",
        type: "select",
        defaultValue: "5",
        options: [
          { value: "5", label: "5 dB (OSHA)" },
          { value: "3", label: "3 dB (ACGIH / EU)" },
        ],
      },
    ],
  },
  {
    slug: "hav-calculator",
    name: "Hand-Arm Vibration Calculator",
    category: "exposure",
    shortDescription: "HAV A(8) daily vibration exposure",
    seoTitle: "Hand-Arm Vibration A(8) Calculator — HSE UK L140 / ISO 5349",
    seoDescription:
      "Calculate Hand-Arm Vibration A(8) daily exposure. HSE UK EAV = 2.5 m/s², ELV = 5.0 m/s². Critical for construction, power tools, drilling.",
    keywords: [
      "hand arm vibration calculator",
      "HAV calculator",
      "HAVS",
      "vibration white finger",
      "HSE L140",
      "ISO 5349",
      "EU vibration directive",
      "construction HAV",
      "power tools vibration",
    ],
    formula: "A(8) = a × √(T / 8)",
    regulation: "HSE UK L140 / ISO 5349-1 / EU 2002/44/EC",
    inputs: [
      {
        id: "vibrationMs2",
        label: "Vibration magnitude (m/s²)",
        type: "number",
        min: 0,
        max: 30,
        step: 0.1,
        defaultValue: 4.2,
      },
      {
        id: "exposureHours",
        label: "Exposure duration (hours)",
        type: "number",
        min: 0,
        max: 24,
        step: 0.25,
        defaultValue: 3,
      },
    ],
  },
  {
    slug: "wbv-calculator",
    name: "Whole-Body Vibration Calculator",
    category: "exposure",
    shortDescription: "WBV A(8) daily exposure",
    seoTitle: "Whole-Body Vibration A(8) Calculator — ISO 2631-1 / EU 2002/44/EC",
    seoDescription:
      "Whole-body vibration daily exposure A(8). EAV = 0.5 m/s², ELV = 1.15 m/s². For haulage, forklift, excavator operators.",
    keywords: [
      "whole body vibration calculator",
      "WBV calculator",
      "ISO 2631",
      "haulage driver vibration",
      "forklift vibration",
      "excavator operator",
      "EU vibration directive",
    ],
    formula: "A(8) = k × a × √(T / 8)",
    regulation: "ISO 2631-1 / EU 2002/44/EC",
    inputs: [
      {
        id: "vibrationMs2",
        label: "Vibration magnitude (m/s²)",
        type: "number",
        min: 0,
        max: 5,
        step: 0.01,
        defaultValue: 0.8,
      },
      {
        id: "exposureHours",
        label: "Exposure hours",
        type: "number",
        min: 0,
        max: 24,
        step: 0.25,
        defaultValue: 6,
      },
      {
        id: "axis",
        label: "Axis",
        type: "select",
        defaultValue: "z",
        options: [
          { value: "z", label: "Z (vertical) — k=1.0" },
          { value: "x", label: "X (fore-aft) — k=1.4" },
          { value: "y", label: "Y (lateral) — k=1.4" },
        ],
      },
    ],
  },

  // ── Environmental ─────────────────────────────────────────────────────
  {
    slug: "wbgt-calculator",
    name: "WBGT Heat Stress Calculator",
    category: "environmental",
    shortDescription: "Wet Bulb Globe Temperature",
    seoTitle: "WBGT Calculator — Wet Bulb Globe Temperature (ACGIH TLV / ISO 7243)",
    seoDescription:
      "Free WBGT heat stress calculator. Outputs work/rest ratio per ACGIH TLV. Critical for GCC summer working conditions, OSHAD heat safety, midday-work ban compliance.",
    keywords: [
      "WBGT calculator",
      "wet bulb globe temperature",
      "heat stress calculator",
      "ACGIH TLV heat",
      "ISO 7243",
      "midday break UAE",
      "Saudi midday ban",
      "GCC heat safety",
      "OSHAD heat stress",
      "construction heat safety",
      "NIOSH heat",
    ],
    formula: "WBGT = 0.7·Tw + 0.2·Tg + 0.1·Td (outdoor with sun)",
    regulation: "ACGIH TLV / ISO 7243",
    inputs: [
      { id: "tempC", label: "Dry bulb temp (°C)", type: "number", min: -20, max: 60, step: 0.1, defaultValue: 38 },
      { id: "humidity", label: "Relative humidity (%)", type: "number", min: 0, max: 100, step: 1, defaultValue: 60 },
      { id: "globeTempC", label: "Globe temp (°C)", type: "number", min: -20, max: 80, step: 0.1, defaultValue: 42 },
      {
        id: "indoor",
        label: "Environment",
        type: "select",
        defaultValue: "outdoor",
        options: [
          { value: "outdoor", label: "Outdoor (with solar load)" },
          { value: "indoor", label: "Indoor (no solar)" },
        ],
      },
    ],
  },
  {
    slug: "carbon-footprint-calculator",
    name: "Carbon Footprint Calculator",
    category: "environmental",
    shortDescription: "Scope 1+2+3 CO₂e (GHG Protocol)",
    seoTitle: "Carbon Footprint Calculator — GHG Protocol Scope 1+2+3 (CO₂e)",
    seoDescription:
      "Free GHG Protocol Scope 1/2/3 carbon footprint calculator. Emission factors for UAE, KSA, UK, US. Required for ESG reporting and ISO 14064-1.",
    keywords: [
      "carbon footprint calculator",
      "CO2e calculator",
      "GHG Protocol",
      "Scope 1 Scope 2 Scope 3",
      "ISO 14064",
      "ESG reporting",
      "net zero",
      "carbon accounting",
      "CDP disclosure",
      "UAE emissions factor",
      "KSA emissions factor",
    ],
    formula: "Total = Scope1 + Scope2 + Scope3",
    regulation: "GHG Protocol / ISO 14064-1",
    inputs: [
      { id: "dieselL", label: "Diesel (L) — Scope 1", type: "number", min: 0, step: 10, defaultValue: 0 },
      { id: "electricityKwh", label: "Electricity (kWh) — Scope 2", type: "number", min: 0, step: 100, defaultValue: 0 },
      {
        id: "region",
        label: "Electricity region",
        type: "select",
        defaultValue: "world",
        options: [
          { value: "world", label: "World average" },
          { value: "uae", label: "UAE" },
          { value: "ksa", label: "Saudi Arabia" },
          { value: "uk", label: "UK" },
          { value: "usa", label: "USA" },
        ],
      },
      { id: "flightKmLong", label: "Long-haul flights (km) — Scope 3", type: "number", min: 0, step: 100, defaultValue: 0 },
      { id: "carKm", label: "Business travel car (km) — Scope 3", type: "number", min: 0, step: 10, defaultValue: 0 },
    ],
  },

  // ── Ergonomics ────────────────────────────────────────────────────────
  {
    slug: "niosh-lifting-calculator",
    name: "NIOSH Lifting Calculator",
    category: "ergonomics",
    shortDescription: "Recommended Weight Limit + Lifting Index",
    seoTitle: "NIOSH Lifting Equation Calculator — Recommended Weight Limit + LI",
    seoDescription:
      "Free NIOSH Lifting Equation calculator (1994 revision). Calculates RWL and Lifting Index for manual lifting tasks. ACGIH and HSE UK accepted.",
    keywords: [
      "NIOSH lifting equation",
      "NIOSH calculator",
      "recommended weight limit",
      "RWL calculator",
      "lifting index",
      "manual handling",
      "ergonomic risk",
      "musculoskeletal disorder",
      "HSE manual handling",
    ],
    formula: "RWL = LC × HM × VM × DM × AM × FM × CM;  LI = Load / RWL",
    regulation: "NIOSH Publication 94-110",
    inputs: [
      { id: "horizontalCm", label: "Horizontal distance H (cm)", type: "number", min: 0, max: 100, step: 1, defaultValue: 30 },
      { id: "verticalCm", label: "Vertical origin V (cm)", type: "number", min: 0, max: 175, step: 1, defaultValue: 75 },
      { id: "verticalTravelCm", label: "Vertical travel D (cm)", type: "number", min: 0, max: 175, step: 1, defaultValue: 50 },
      { id: "angleDegrees", label: "Asymmetry angle A (°)", type: "number", min: 0, max: 135, step: 5, defaultValue: 0 },
      { id: "frequencyPerMin", label: "Frequency (lifts/min)", type: "number", min: 0, max: 15, step: 0.1, defaultValue: 2 },
      { id: "durationHours", label: "Duration (hours)", type: "number", min: 0, max: 8, step: 0.5, defaultValue: 4 },
      {
        id: "couplingQuality",
        label: "Grip / coupling",
        type: "select",
        defaultValue: "good",
        options: [
          { value: "good", label: "Good (cutouts / handles)" },
          { value: "fair", label: "Fair" },
          { value: "poor", label: "Poor" },
        ],
      },
      { id: "loadKg", label: "Actual load (kg)", type: "number", min: 0, max: 100, step: 0.5, defaultValue: 15 },
    ],
  },
  {
    slug: "manual-handling-calculator",
    name: "Manual Handling MAC Calculator",
    category: "ergonomics",
    shortDescription: "HSE UK Manual Assessment Charts",
    seoTitle: "Manual Handling MAC Calculator — HSE UK Risk Banding",
    seoDescription:
      "Free manual handling risk assessment using HSE UK MAC tool bands. Green/Amber/Red output with intervention recommendations.",
    keywords: [
      "manual handling calculator",
      "HSE MAC tool",
      "manual handling risk assessment",
      "lifting risk",
      "back injury prevention",
      "construction manual handling",
      "warehouse safety",
    ],
    formula: "Weighted score: load + distance + frequency + posture",
    regulation: "HSE UK MAC tool",
    inputs: [
      { id: "loadKg", label: "Load (kg)", type: "number", min: 0, max: 100, step: 0.5, defaultValue: 15 },
      { id: "distanceM", label: "Carry distance (m)", type: "number", min: 0, max: 200, step: 0.5, defaultValue: 5 },
      { id: "frequencyPerHour", label: "Frequency (per hour)", type: "number", min: 0, max: 200, step: 1, defaultValue: 10 },
    ],
  },

  // ── Fire ──────────────────────────────────────────────────────────────
  {
    slug: "fire-load-calculator",
    name: "Fire Load Calculator",
    category: "fire",
    shortDescription: "Fire load density (MJ/m²)",
    seoTitle: "Fire Load Density Calculator — NFPA 557 / BS 9999 (MJ/m²)",
    seoDescription:
      "Calculate fire load density for building compartments. Classifications: low/moderate/high/very high. Required for fire risk assessments.",
    keywords: [
      "fire load calculator",
      "fire load density",
      "NFPA 557",
      "BS 9999",
      "fire risk assessment",
      "fire engineering",
      "Eurocode fire",
      "building fire safety",
    ],
    formula: "FL = Σ (Mass × Calorific Value) / Floor Area",
    regulation: "NFPA 557 / BS 9999 / EN 1991-1-2",
    inputs: [
      { id: "floorAreaM2", label: "Floor area (m²)", type: "number", min: 1, max: 100_000, step: 1, defaultValue: 500 },
      { id: "woodKg", label: "Wood (kg)", type: "number", min: 0, step: 10, defaultValue: 2000 },
      { id: "paperKg", label: "Paper / cardboard (kg)", type: "number", min: 0, step: 10, defaultValue: 500 },
      { id: "plasticKg", label: "Plastics (kg)", type: "number", min: 0, step: 10, defaultValue: 300 },
    ],
  },
  {
    slug: "evacuation-time-calculator",
    name: "Evacuation Time (RSET) Calculator",
    category: "fire",
    shortDescription: "Required Safe Egress Time",
    seoTitle: "Evacuation Time Calculator — Required Safe Egress Time (RSET, NFPA 101)",
    seoDescription:
      "Calculate RSET per NFPA 101 / BS 9999: pre-movement + travel time + flow time through exits. Required for fire risk assessments.",
    keywords: [
      "evacuation time calculator",
      "RSET",
      "required safe egress time",
      "NFPA 101",
      "BS 9999",
      "fire evacuation",
      "emergency egress",
      "SFPE handbook",
    ],
    formula: "RSET = pre-movement + travel + flow",
    regulation: "NFPA 101 / BS 9999 / SFPE Handbook",
    inputs: [
      { id: "occupants", label: "Occupants", type: "number", min: 1, max: 10_000, step: 1, defaultValue: 200 },
      { id: "travelDistanceM", label: "Travel distance (m)", type: "number", min: 1, max: 500, step: 1, defaultValue: 30 },
      { id: "exitWidthM", label: "Total exit width (m)", type: "number", min: 0.5, max: 50, step: 0.1, defaultValue: 2.4 },
      { id: "preMovementTimeS", label: "Pre-movement time (s)", type: "number", min: 0, max: 600, step: 10, defaultValue: 60 },
    ],
  },

  // ── Workload ──────────────────────────────────────────────────────────
  {
    slug: "manhours-calculator",
    name: "Manhours Calculator",
    category: "workload",
    shortDescription: "Total exposure hours",
    seoTitle: "Manhours Calculator — Total Worked Hours with Overtime (Free)",
    seoDescription:
      "Calculate total exposure hours for HSE KPI reporting. Supports overtime. Inputs for TRIR/LTIR/LTIFR calculators downstream.",
    keywords: [
      "manhours calculator",
      "man hours calculator",
      "total hours worked",
      "exposure hours",
      "HSE KPI",
      "OSHA hours worked",
      "safety reporting",
      "construction manhours",
      "GCC manhours",
    ],
    formula: "Total = Workers × Hours/Day × Days × (1 + Overtime %)",
    regulation: "OSHA / ISO 45001 reporting convention",
    inputs: [
      { id: "workers", label: "Workers", type: "number", min: 1, step: 1, defaultValue: 150 },
      { id: "hoursPerDay", label: "Hours per day", type: "number", min: 1, max: 24, step: 0.5, defaultValue: 10 },
      { id: "days", label: "Days", type: "number", min: 1, step: 1, defaultValue: 22 },
      { id: "overtimePct", label: "Overtime (%)", type: "number", min: 0, max: 100, step: 1, defaultValue: 15 },
    ],
  },

  // ── Risk ──────────────────────────────────────────────────────────────
  {
    slug: "risk-matrix-calculator",
    name: "Risk Matrix Calculator",
    category: "risk",
    shortDescription: "5×5 or 4×4 risk matrix scoring",
    seoTitle: "Risk Matrix Calculator — 5×5 Likelihood × Severity (ISO 45001 / Aramco / ADNOC)",
    seoDescription:
      "Free 5×5 and 4×4 risk matrix calculator with ISO 45001 / Aramco SAIC-SS / ADNOC / QatarEnergy bands. Low/Medium/High/Extreme classification with action guidance.",
    keywords: [
      "risk matrix calculator",
      "5x5 risk matrix",
      "risk assessment matrix",
      "likelihood severity matrix",
      "ISO 45001 risk",
      "Aramco SAIC-SS",
      "ADNOC risk",
      "QatarEnergy risk",
      "oil and gas risk assessment",
      "construction risk assessment",
    ],
    formula: "Risk = Likelihood × Severity",
    regulation: "ISO 45001:2018 / IEC 31010",
    inputs: [
      { id: "likelihood", label: "Likelihood (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 4 },
      { id: "severity", label: "Severity (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 5 },
      {
        id: "matrix",
        label: "Matrix size",
        type: "select",
        defaultValue: "5x5",
        options: [
          { value: "5x5", label: "5 × 5 (oil & gas standard)" },
          { value: "4x4", label: "4 × 4 (construction standard)" },
        ],
      },
    ],
  },
  {
    slug: "safety-score-calculator",
    name: "Safety Score Calculator",
    category: "risk",
    shortDescription: "Composite HSE performance KPI",
    seoTitle: "Safety Score Calculator — Composite HSE Performance KPI (0-100)",
    seoDescription:
      "Weighted safety score combining TRIR, LTIFR, near-miss reporting, training completion, audit compliance. Outputs A-F grade.",
    keywords: [
      "safety score calculator",
      "HSE KPI calculator",
      "safety performance",
      "HSE dashboard",
      "ISO 45001 KPI",
      "safety scorecard",
      "leading indicators",
      "lagging indicators",
    ],
    formula: "Weighted average across TRIR, LTIFR, near-miss, training, audit",
    regulation: "ISO 45001 Clause 9.1 (monitoring & measurement)",
    inputs: [
      { id: "trir", label: "TRIR", type: "number", min: 0, max: 20, step: 0.1, defaultValue: 1.5 },
      { id: "ltifr", label: "LTIFR", type: "number", min: 0, max: 20, step: 0.1, defaultValue: 2.0 },
      { id: "nearMissReporting", label: "Near-miss ratio (:recordables)", type: "number", min: 0, max: 100, step: 0.5, defaultValue: 8 },
      { id: "trainingComplete", label: "Training complete (%)", type: "number", min: 0, max: 100, step: 1, defaultValue: 92 },
      { id: "auditCompliance", label: "Audit compliance (%)", type: "number", min: 0, max: 100, step: 1, defaultValue: 88 },
    ],
  },
  {
    slug: "stress-risk-calculator",
    name: "Work Stress Risk Calculator",
    category: "risk",
    shortDescription: "HSE UK Management Standards",
    seoTitle: "Work-Related Stress Risk Calculator — HSE UK Management Standards",
    seoDescription:
      "Assess work-related stress risk across 6 HSE UK Management Standards: demands, control, support, relationships, role, change.",
    keywords: [
      "work stress calculator",
      "HSE stress management",
      "psychosocial risk",
      "mental health at work",
      "ISO 45003",
      "stress risk assessment",
    ],
    formula: "Average across 6 HSE Management Standards (1-5)",
    regulation: "HSE UK Management Standards / ISO 45003",
    inputs: [
      { id: "demands", label: "Demands (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 3 },
      { id: "control", label: "Control (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 3 },
      { id: "support", label: "Support (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 4 },
      { id: "relationships", label: "Relationships (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 4 },
      { id: "role", label: "Role (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 4 },
      { id: "change", label: "Change (1-5)", type: "number", min: 1, max: 5, step: 1, defaultValue: 3 },
    ],
  },
];

export function getCalculator(slug: string): CalculatorMeta | undefined {
  return CALCULATORS.find((c) => c.slug === slug);
}
